# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.cache/wt [current_project]
set_property parent.project_path E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths work/Viva161_ip/XUP_74LSXX_Lib [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/imports/lab2/led_ctl.v
  E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/imports/lab2/meta_harden.v
  E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/imports/lab2/uart_baud_gen.v
  E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/imports/lab2/uart_rx.v
  E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/imports/lab2/uart_rx_ctl.v
  E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/imports/lab2/uart_led.v
}
read_ip -quiet E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/ip/ila_0_9/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/ip/ila_0_9/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/ip/ila_0_9/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/ip/ila_0_9/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/sources_1/ip/ila_0_9/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/constrs_1/new/A7_uart_led.xdc
set_property used_in_implementation false [get_files E:/SC_Vivado/A7_uart_led_debug_demo_7A35T/debug_demo.srcs/constrs_1/new/A7_uart_led.xdc]


synth_design -top uart_led -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uart_led.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uart_led_utilization_synth.rpt -pb uart_led_utilization_synth.pb"
