# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/SC_Vivado/counter/counter.cache/wt [current_project]
set_property parent.project_path E:/SC_Vivado/counter/counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/SC_Vivado/counter/User_IP [current_project]
set_property ip_output_repo e:/SC_Vivado/counter/counter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/SC_Vivado/counter/counter.srcs/sources_1/bd/counter/hdl/counter_wrapper.v
add_files E:/SC_Vivado/counter/counter.srcs/sources_1/bd/counter/counter.bd
set_property used_in_implementation false [get_files -all e:/SC_Vivado/counter/counter.srcs/sources_1/bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/SC_Vivado/counter/counter.srcs/sources_1/bd/counter/counter_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/SC_Vivado/counter_seg7_EGo/xdc/counter_seg7_EGo1.xdc
set_property used_in_implementation false [get_files E:/SC_Vivado/counter_seg7_EGo/xdc/counter_seg7_EGo1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top counter_wrapper -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef counter_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file counter_wrapper_utilization_synth.rpt -pb counter_wrapper_utilization_synth.pb"
