# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/SC_Vivado/counter_seg7_EGo/xdc/counter_seg7_EGo1.xdc

# Block Designs: bd/counter/counter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter || ORIG_REF_NAME==counter} -quiet] -quiet

# IP: bd/counter/ip/counter_clk_div_10Hz_0_0/counter_clk_div_10Hz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_clk_div_10Hz_0_0 || ORIG_REF_NAME==counter_clk_div_10Hz_0_0} -quiet] -quiet

# IP: bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_c_counter_binary_0_0 || ORIG_REF_NAME==counter_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/counter/ip/counter_seg7_hex_0_0/counter_seg7_hex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_seg7_hex_0_0 || ORIG_REF_NAME==counter_seg7_hex_0_0} -quiet] -quiet

# XDC: bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0_ooc.xdc

# XDC: bd/counter/counter_ooc.xdc
